### PR TITLE
Implementation of jellium model (Part 3)

### PR DESCRIPTION
**Pull request by tt-ims**
This PR adds jellium model for RT calculation.

### CODE REVIEW

**Comment by tt-ims** [comment]
test this please

**Comment by tt-ims** [comment]
retest this please

**Comment by tt-ims** [comment]
retest this please

**Comment by tt-ims** [comment]
retest this please

**Comment by tt-ims** [comment]
retest this please

**Comment by tt-ims** [comment]
retest this please

**Review by syamada0 — APPROVED** [review]

**Comment by tt-ims** [comment]
retest this please

**Comment by tt-ims** [comment]
retest this please

**Comment by tt-ims** [comment]
retest this please

**Pull request merged**
